version: '3'

services:
  # Database
  pokedexdb:
    image: mongo:6
    container_name: pokedexdb
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - /mongo:/data/db
    networks:
      - pokedex
  # Api
  pokedexapi:
    depends_on:
      - pokedexdb
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-api-nestjs
    container_name: pokedexapi
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      MONGO_DB_CONNECTION_STRING: ${MONGO_DB_CONNECTION_STRING}
    networks:
      - pokedex

networks:
  pokedex: